---
title: "Informe grupal"
subtitle: "Ecología de poblaciones silvestres"
abstract: |
  The abstract of the article.
  
authors:
- name: |

      Diego Monge-Villegas, 
      Paul Oviedo,
      Natalia Villalobos-Sequeira,
      Eylin Flores-Zuñiga,
      Marlon Guerrero,
      Jose Guillermo Ramirez Bogantes,
      Jessica Jimenes Loria
      
  affiliation: Escuela de Ciencias Biológicas, Universidad Nacional
date:  "`r format(Sys.Date(), '%d de %B, %Y')`"
publisher: "Some Publisher"
output: DMtemplates::APAreport
latex_engine: xelatex
toc: true
toc-depth: 2
lof: true
lot: true
number_sections: true
papersize: letter
fontsize: 12pt
documentclass: article
classoption: twoside, openright
language: "spanish"
secnumdepth: 1
geometry: "top=2.5cm, bottom=2.5cm, left=3cm, right=3cm"
fancyHeader: true
mainfont: Cambria
mathfont: Cambria
sansfont: Arial
preamble: |
    \usepackage{fancyhdr}
    
    \pagestyle{fancy}
    
    \lhead{APA Template}
    
    \rhead{D. Martinez}
    
    \setlength\parindent{24pt}
    
    \setlength{\parskip}{12pt}
    
    \usepackage{setspace}
    
    \singlespacing
    
    \counterwithin{figure}{chapter}
    
    \counterwithin{table}{chapter}
    
    \newtheorem{theorem}{Teorema}
    
    \newtheorem{algorithm}{Algoritmo}

    \newtheorem{axiom}{Axioma}
    
    \newtheorem{definition}{Definición}

    \newtheorem{example}{Ejemplo}
    
    \newtheorem{exercise}{Ejercicio}
    
    \newtheorem{lemma}{Lemma}
    
    \newtheorem{proposition}{Proposición}
    
    \newtheorem{remark}{Remarca}
    
    \newtheorem{solution}{Solución\;\thesection\,.}
    
    \newtheorem{summary}{Resumen}
    
bibliography: ExampleBIB.bib
csl: apa.csl
urlcolor: blue
citecolor: black
linkcolor: black
year: "`r as.POSIXlt(Sys.time())$year+1900`"
spacing: siglespacing
---

```{r settings}
knitr::knit_hooks$set(inline = identity) 
```


# Para correr esta plantilla

En la consola de R, correr

```
install.packages("devtools")
devtools::install_github("dawidh15/DMtemplates")
```

# Introducción  Tarea del 26 de abril. 

 Strombus gigas, es un gasterópodo muy importante comercialmente en muchos de los lugares donde se distribuye, la carne de este caracol es conocida por ser una buena fuente de alimento y proteína, ademas la concha es comercializada con propósitos ornamentales [@Forbes Pacheco2011].
 
 Es un molusco de gran tamaño, alcanza unos 25 cm de longitud en la concha después de 3 a 4 años y en este momento son sexualmente maduros, habitan en aguas poco profundas, a menos de 50 m de profundidad en la mayoría de los casos y se ubican de la región del Atlántico occidental, desde Bermudas en el norte hasta el Golfo de México, la parte del Gran Caribe y la costa del norte de América del Sur [@Garcia Rodriguez2016].
 
 En la costa del Pacífico americano, los caracoles del género Strombus, mejor conocidos como cambute, se distribuyen desde el Golfo de México hasta las islas Galápagos. En Costa Rica es posible hallar estos caracoles a lo largo de toda la costa, principalmente en zonas rocosas y poco profundas.  En el sector San Miguel del Refugio Nacional de Vida Silvestre Cabo Blanco, se estimó la población de Strombus galeatus en 627 individuos, donde el adulto con mayor peso alcanzó  2 775 g y el juvenil más pequeño pesó 50 g. A nivel etario es posible separar los individuos de cambute en tres clases de edades (adultos, subadultos y juveniles), de acuerdo con la biometría de su concha (largo, ancho y grosor del labio). Por ejemplo, se estima que el largo medio de la concha de los adultos es de 183,2 ± 9,5 mm, mientras que el ancho medio de la concha es de 146,5 ± 11,1 mm [@mora1998estructura].
 
La población de Strombus galeatus en lugares como: Panamá, Mexico, Ecuador y otros lugares del Pacifico muestran una baja tasa de crecimiento en los últimos años. Esta situación se relaciona con la explotación masiva sin regulaciones provocada por el ser humano para el consumo de este molusco. El cual es una especie importante para la economía local de muchos sectores y a menudo compite con los planes de conservación [@Castellanos-Galindo2011]. Al aplicar un programa de monitoreo y de información a los pescadores se convierte en una alternativa para combatir tal efecto en la mortalidad de la especie y que las poblaciones de galeatus pueden restaurarse con éxito.

Los modelos de crecimiento en esta especie son utilizados en muchos estudios con el fin de determinar si la población se encuentra en declive o en aumento, después de que se prohíbe o se permite la extracción comercial de este caracol, tal es el caso de una investigacion realizada en Panama donde detectan que cinco años después de haber prohibido la pesca de cambute, la población de estos en Las Perlas y Coiba Archipelagos no se encuentra en aumento, enconrando principalmente individuos adultos [@Cipriani2008].

Se encuntra informacion donde se adaptó un modelo de crecimiento de von Bertalanffy a datos de juveniles específicamente, utilizando los siguientes parámetros: $L_\infty$ = 315 mm, K = 0.029 mo -1 , y t o = 0.5 meses. En el cual llegaron a observar que la apariencia de un labio delgado es considerado un criterio pobre para la madurez sexual y entre mayor sea este es recomendado para lograr la protección de las poblaciones bajo una fuerte presión de pesca y así mismo que las poblaciones de Galeatus pueden restablecerse con éxito [@Cipriani2008].


Este habla del desarrollo, desove y maduracion de S.Pectinata, tiene unos graficos interesante sobre crecimiento vs tiempo [@caña1999maturation]








Si el estudiante no está familiarizado con las herramientas de búsqueda bibliográfica y bases de datos suscritas por la Universidad Nacional, es su responsabilidad informarse con la bibliotecaria de la Unidad Académica.



[@mora1998estructura]
[@arroyo2008caracteristicas]
[@vega2003crecimiento]
[@avila2009reproductive]
[@perez2003actividad]
[@ortega1985competitive]
[@giraldo1999variacion]
[@liu1994distribution]
[@branch1994intertidal]
[@Pinchuck2009]
[@Cipriani2008]
[@Castellanos-Galindo2011]
[@ortega1987effect]
[@hugheshabitat]
[@sibaja2010temporal]
[@cigliano2014density]
[@cipriani2008population]
[@forbes2017evaluacion]
[@garcia2016queen]
[@kough2017efficacy]
[@morris2016distribution]
[@vega2003crecimiento]
[@appeldoorn1988age]
[@de2000crecimiento]


# Metodología

El sitio de estudio fue el mismo utilizado por Ortega (1985) en un cabo llamado punta mala en el pacifico central de Costa Rica el ambiente presenta una estacion seca desde diciembre hasta abril y  una temporada de lluvias desde mayo hasta noviembre. en la parte sur de cabo es una proyeccion de bancos de arena. 

Intervalos de clasificacion

Se considera como juveniles losindividuos que midan mas de 87 mm y manos de 150 mm, como subadultos los que midan mas de 150 mm y manos de 170 mm y los adultos seran los que midan mas de 170 mm.




Definir el procedimiento de análisis. Se basarán en la teoría, en las investigaciones individuales, y en una búsqueda general en línea, para escoger un procedimiento de análisis que permita **calcular la probabilidad de extinción de las poblaciones de interés a cinco años**.

Diseño de muestreo. Solo hay tiempo para un sitio por población. Por tanto, el diseño de muestreo se refiere al establecimiento de las variables que se deben medir en el campo, a los formularios de campo, al procedimiento para tomar los datos y al diseño de la base de datos (se *recomienda* una base de **LibreOffice Base**).

# Resultados

Aquí se presentará la estimación de la probabilidad de extinción a 5 años para cada especie. También cualquier resultado que surge como paso intermedio para calcular la probabilidad de extinción.

# Discusión

Discutiremos sobre la validez de los resultados, en función de los datos obtenidos y los requerimientos del análisi de datos

# Cuadros

Para cambiar la fuente, el espaciado y referenciar el cuadro, ver siguiente ejemplo: \index{cuadros y su formato}


\begingroup
\sffamily
\small

\singlespacing

    
| Unidad | Equivalencia en SI|
|------------:|----------:|
| 1 vara | \SI{0.8393}{\metre}|
| 1 cuarta | \SI{0.209825}{\metre}|
| 1 tercia | \SI{0.2797}{\metre}|
| 1 mecate | \SI{20.1432}{\metre}|
| 1 manzana | \SI{6960.6}{\metre\squared}
| 1 caja | \SI{16}{\kilogram}|
| 1 fanega | \SI{92}{\kilogram}|
| 1 carga | \SI{161}{\kilogram}|
| 1 botella | \SI{0.63}{\litre}|
| 1 cajuela | \SI{16.6}{\litre}|


Table: (\#tab:OldUnits) Unidades antiguas utilizadas en Costa Rica, y su equivalencia con el Sistema Internacional de Unidades.
\index{cuadros. Encabezados y referencias}

\endgroup

# Bibliografía {-}


\setlength{\parindent}{-0.2in}
\setlength{\leftskip}{0.2in}
\setlength{\parskip}{8pt}
\noindent
